//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FanCtrl.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLib() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FanCtrl.Resources.StringLib", typeof(StringLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align digits :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_digits {
            get {
                return ResourceManager.GetString("Align_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Fan Control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auto_Fan_Control {
            get {
                return ResourceManager.GetString("Auto_Fan_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to change the color?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Change_the_color {
            get {
                return ResourceManager.GetString("Change_the_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中文과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLC Lighting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CLC_Lighting {
            get {
                return ResourceManager.GetString("CLC_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clients과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Default_color {
            get {
                return ResourceManager.GetString("Default_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay(sec) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delay_Time {
            get {
                return ResourceManager.GetString("Delay_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data cannot be added because there are duplicate key!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Duplicate_Key {
            get {
                return ResourceManager.GetString("Duplicate_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable automatic fan control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enable_automatic_fan_control {
            get {
                return ResourceManager.GetString("Enable_automatic_fan_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable OSD (RTSS)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enable_OSD {
            get {
                return ResourceManager.GetString("Enable_OSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ETC {
            get {
                return ResourceManager.GetString("ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fahrenheit (°F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read preset file!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Failed_to_read_preset_file {
            get {
                return ResourceManager.GetString("Failed_to_read_preset_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fan {
            get {
                return ResourceManager.GetString("Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fan_control {
            get {
                return ResourceManager.GetString("Fan_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fan_speed {
            get {
                return ResourceManager.GetString("Fan_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Français과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deutsch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Groups과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HotKey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hysteresis : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Hysteresis {
            get {
                return ResourceManager.GetString("Hysteresis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IP_address {
            get {
                return ResourceManager.GetString("IP_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kraken Lighting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kraken_Lighting {
            get {
                return ResourceManager.GetString("Kraken_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lighting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   liquidctl Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string liquidctl_Setting {
            get {
                return ResourceManager.GetString("liquidctl_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Localize {
            get {
                return ResourceManager.GetString("Localize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Made by Lich과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Made1 {
            get {
                return ResourceManager.GetString("Made1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (lich426@gmail.com)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Made2 {
            get {
                return ResourceManager.GetString("Made2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The hardware and Control.json file do not match!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Not_Match {
            get {
                return ResourceManager.GetString("Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to change the library?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OptionChange {
            get {
                return ResourceManager.GetString("OptionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reset?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OptionReset {
            get {
                return ResourceManager.GetString("OptionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PawnIO is not installed, do you want to install it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PawnIO_install {
            get {
                return ResourceManager.GetString("PawnIO_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PawnIO is outdated, do you want to update it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PawnIO_update {
            get {
                return ResourceManager.GetString("PawnIO_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Port_number {
            get {
                return ResourceManager.GetString("Port_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NZXT RGB＆Fan Controller Lighting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RGBnFC_Lighting {
            get {
                return ResourceManager.GetString("RGBnFC_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Русский과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Server_Start {
            get {
                return ResourceManager.GetString("Server_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Server_Stop {
            get {
                return ResourceManager.GetString("Server_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Set_color {
            get {
                return ResourceManager.GetString("Set_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show system time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Show_system_time {
            get {
                return ResourceManager.GetString("Show_system_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Silence {
            get {
                return ResourceManager.GetString("Silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   español과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start minimized과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start_minimized {
            get {
                return ResourceManager.GetString("Start_minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start with Windows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start_with_Windows {
            get {
                return ResourceManager.GetString("Start_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target temperature sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Target_Temp {
            get {
                return ResourceManager.GetString("Target_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FanCtrl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Icon animation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tray_Icon_animation {
            get {
                return ResourceManager.GetString("Tray_Icon_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open socket!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unable_to_open_socket {
            get {
                return ResourceManager.GetString("Unable_to_open_socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
